entities:
  seaf.ba.products:
    schema:
      patternProperties:
        "[a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]*)*$":
          properties:
            sber:
              type: object
              additionalProperties: false
              properties:
                id:
                  type: string
                  title: Идентификатор продукта
                systems:
                  title: Связи с АС
                  type: array
                  items:
                    $ref: "#/$rels/components.component"
                status:
                  title: Статус
                  enum:
                    - Создается
                    - Используется
                    - Выводится
                    - В архиве
                comments:
                  title: Комментарии, риски, проблемы
                  type: array
                  items:
                    type: string
              oneOf:
                - type: object
                  properties:
                    subtype:
                      type: string
                      title: Подтип продукта
                      enum:
                        - Канал
                    type:
                      title: Тип канала
                      enum:
                        - Цифровой
                        - Физический
                        - Смешанный
                    security:
                      title: Способы защиты канала
                      type: string
                  required:
                    - subtype
                    - type
                    - security
                - type: object
                  properties:
                    subtype:
                      type: string
                      title: Подтип продукта
                      default: Продукт
                      enum:
                        - Продукт
              required:
                - status
