entities:
  seaf.ba.products:
    schema:
      patternProperties:
        "[a-zA-Z0-9_]*(\\.[a-zA-Z0-9_]*)*$":
          properties:
            systems:
              title: Связи с АС
              type: array
              items:
                $ref: "#/$rels/components.component"
            is_channel:
              title: является каналом
              type: object
              properties: 
                type:
                  title: Тип канала
                  enum:
                    - Цифровой
                    - Физический
                    - Смешанный
                security:
                  title: Способы защиты канала
                  type: string
              required:
                - type
                - security
            status:
              title: Статус
              enum:
                - Создается
                - Используется
                - Выводится
                - В архиве
            comments:
              title: Комментарии, риски, проблемы
              type: array
              items:
                type: string
          required:
            - status
