rules:
  validators:
    seaf.ta.components.k8s_deployment.existence:
      uid: k8s_deployment-error-existence
      description: >
        Должны быть определены и описаны k8s deployment
      title: Наличие k8s deployment
      source: >
        (
            
              $fn := $.seaf_dzo_core."validation.functions"."k8s_deployment";
              $domain := sber.domain;
              $result := $eval($fn);
          
              [$result.iserrors = true ? (
                  {
                      "uid": $self.uid & '-01',
                      "title": "Отсутствуют k8s deployment",
                      "location": "entities/seaf.ta.components.k8s_deployment/registry?domain=" & $domain,
                      "correction": 'Необходимо заполнить сущность "seaf.ta.components.k8s_deployment"',
                      "description": $self.description
                  }
              )]
            
        )