entities:
  seaf.app.services:
    title: Прикладной сервис
    description: Прикладной сервис
    objects:
      app.service:
        route: "/"
        title: Прикладной сервис
    schema:
      patternProperties:
        "^[a-zA-Z][a-zA-Z0-9_-]*(\\.[a-zA-Z0-9][a-zA-Z0-9_-]*)*$":
          type: object
          allOf:
            - $ref: "#/$defs/seaf.app.sber.service"
          properties:
            title:
              title: Название прикладного сервиса
              type: string
            description:
              title: Описание прикладного сервиса
              type: string